dataset:
  quality_indicators:
  - type: dataset
    quality_dimension_id: egnethet_reguleringsplan
    quality_warning_text: Datasettet er lite egnet for reguleringsplan
    warning_threshold: 0 OR 1 OR 2
    input_filter: context = 'Reguleringsplan'

  - type: dataset
    quality_dimension_id: egnethet_kommuneplan
    quality_warning_text: Datasettet er lite egnet for kommuneplan
    warning_threshold: 0 OR 1 OR 2
    input_filter: context = 'Kommuneplan'

  - type: dataset
    quality_dimension_id: egnethet_byggesak
    quality_warning_text: Datasettet er lite egnet for byggesak
    warning_threshold: 0 OR 1 OR 2
    input_filter: context = 'Byggesak'
