dataset:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d

  quality_indicators:
  - type: object
    quality_dimension_id: stedfestingsnøyaktighet
    quality_warning_text: Data kan være utfordrende å bruke i plan- eller byggesak
    property: Nøyaktighetsklasse
    warning_threshold: Mindre god (> 50m)
