dataset:
  dataset_id: 64cbb884-a19d-4356-a114-380cfe4a7314

  quality_indicators:
  - type: object
    quality_dimension_id: stedfestingsnøyaktighet
    quality_dimension_name: Stedfestingsnøyaktighet
    quality_warning_text: Data kan være utfordrende å bruke i plan- eller byggesak
    property: Nøyaktighetsklasse
    warning_threshold: Mindre god (> 50m)
