dataset:
  dataset_id: fbb95c67-623f-430a-9fa5-9cfcea8366b3

  quality_indicators:
  - type: coverage
    quality_dimension_id: fullstendighet_dekning
    quality_dimension_name: Fullstendighetsdekning
    quality_warning_text: Området er ikke kartlagt
    warning_threshold: ikkeKartlagt
    wfs:
      url: https://wfs.geonorge.no/skwms1/wfs.stormflo_havniva
      layer: Dekningsområde
      geom_field: område
      property: dekningStatus
