# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "DOK.Arealanalyse.demonstrator"
  tags: []
spec:
  type: "experiment"
  lifecycle: "experiment"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
