stormflo:
  dataset_id: fbb95c67-623f-430a-9fa5-9cfcea8366b3
  wfs: https://wfs.geonorge.no/skwms1/wfs.stormflo_havniva
  wms: https://wms.geonorge.no/skwms1/wms.stormflo_havniva
  namespace: https://skjema.geonorge.no/SOSI/produktspesifikasjon/StormfloHavniva/20240220
  layers:
  - wfs: app:Stormflo20År_KlimaÅrNå
    wms: 
    - stormflo20ar_klimaarna
    result_status: HIT-RED
    geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
  - wfs: app:Stormflo200År_KlimaÅrNå
    wms: 
    - stormflo200ar_klimaarna
    result_status: HIT-YELLOW
    geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
  - wfs: app:Stormflo200År_KlimaÅr2100
    wms: 
    - stormflo200ar_klimaar2100
    result_status: HIT-YELLOW
    geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
  geom_element_name: app:område
  properties:
  - app:sikkerhetsklasseFlom
  - app:oppdateringsdato
  - app:opphav
  themes:
  - samfunnssikkerhet

flomsoner:
  dataset_id: e95008fc-0945-4d66-8bc9-e50ab3f50401
  wfs: https://wfs.geonorge.no/skwms1/wfs.flomsoner
  wms: https://nve.geodataonline.no/arcgis/services/Flomsoner1/MapServer/WMSServer
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Flomsoner/1.1
  layers:
  - wfs: app:Analyseområde
    wms: 
    - FlomsoneAnalyseomraade
    - Flomsone_200arsflom
    - Flomsone_200arsflom_klima 
    result_status: HIT-RED
    geolett_id: 5adab8dc-b327-49ed-9336-e85fe2453a05
  geom_element_name: app:område
  properties:
  - app:flomsoneNavn
  - app:kartlagteFlommer
  - app:nedbørfelt
  themes:
  - samfunnssikkerhet

flom_aktsomhets_omr:
  dataset_id: 60c5024f-bf93-4d7a-888a-5fe001427195
  wfs: http://wfs.geonorge.no/skwms1/wfs.flomaktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/FlomAktsomhet/MapServer/WMSServer
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Flomaktsomhetsomrader/1.1
  layers:
  - wfs: app:FlomAktsomhetOmr
    wms: 
    - Flom_aktsomhetsomrade
    result_status: HIT-YELLOW
    geolett_id: 44ef4297-d5a5-4fab-9db3-d67429d7a5f0
  geom_element_name: app:område
  properties:
  - app:vassOmråde
  - app:temaKvalitet
  - app:vannKilde
  themes:
  - samfunnssikkerhet

jord_flomskred_aktsomhets_omr:
  dataset_id: 30e1883e-70e9-4510-9e97-00edbdcddc02
  wfs: https://wfs.geonorge.no/skwms1/wfs.jord_og_flomskred_aktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/SkredJordFlomAktR1/MapServer/WMSServer
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Skredaktsomhet/1.2
  layers:
  - wfs: app:PotensieltSkredfareOmr
    wms: 
    - Potensielt_Jord-Flomskredfare
    result_status: HIT-RED
    geolett_id: 643479b5-41d9-4d66-8069-18f746141a41
  geom_element_name: app:område
  properties:
  - app:skredType
  - app:skredfareVurdering
  - app:temaKvalitet
  - app:oppdateringsdato
  themes:
  - samfunnssikkerhet

snoskred_aktsomhets_omr:
  dataset_id: 54ada9d8-e6fc-48d6-82b0-5477166a4aaa
  wfs: https://wfs.geonorge.no/skwms1/wfs.snoskredaktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/SkredSnoAktR/MapServer/WMSServer
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Skredaktsomhet/1.2
  layers:
  - wfs: app:PotensieltSkredfareOmr
    wms: 
    - Snoskred-Aktsomhetsomrader
    result_status: HIT-RED
    geolett_id: 7831236b-c9c1-4d5f-af4b-cac0304d7d6e
  geom_element_name: app:område
  properties:
  - app:skredType
  - app:skredfareVurdering
  - app:temaKvalitet
  - app:oppdateringsdato
  themes:
  - samfunnssikkerhet

steinsprang_aktsomhets_omr:
  dataset_id: 02c6d51c-4e8c-4948-a620-dc046c8cb747
  wfs: https://wfs.geonorge.no/skwms1/wfs.steinsprang_aktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/SkredSteinAktR/MapServer/WmsServer
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Skredaktsomhet/1.2
  layers:
  - wfs: app:PotensieltSkredfareOmr
    wms: 
    - Steinsprang-AktsomhetOmrader
    result_status: HIT-RED
    geolett_id: 2d405ce6-98ea-40f9-905b-f8a0d5c96224
  geom_element_name: app:område
  properties:
  - app:skredType
  - app:skredfareVurdering
  - app:temaKvalitet
  - app:oppdateringsdato
  themes:
  - samfunnssikkerhet  

faresone_fjellskred:
  dataset_id: 17149f79-1289-4e3c-b964-94113eeb14c8
  arcgis: https://nve.geodataonline.no/arcgis/rest/services/Fjellskred1/MapServer
  wms: https://nve.geodataonline.no/arcgis/services/Fjellskred1/MapServer/WMSServer
  layers:
  - arcgis: 8
    wms: 
    - Faresoner_fjellskred_sammensat    
    result_status: HIT-RED
    geolett_id: a43cee7f-bcc4-44a9-b144-419a0c134a25
  properties:
  - skredOmrNavn
  - skredType
  - skredStatSannsynlighet
  themes:
  - samfunnssikkerhet

faresone_kvikkleireskred:
  dataset_id: b2d5aaf8-79ac-40f3-9cd6-fdc30bc42ea1
  arcgis: https://nve.geodataonline.no/arcgis/rest/services/SkredKvikkleire2/MapServer
  wms: https://nve.geodataonline.no/arcgis/services/SkredKvikkleire2/MapServer/WMSServer
  layers:
  - arcgis: 1
    wms: 
    - KvikkleireRisiko
    result_status: HIT-RED
    geolett_id: 2e84d54f-9e93-4559-8214-8cb21567fa04
  properties:
  - skredOmrNavn
  - faregrad
  - konsekvens
  - risiko
  - rapportURL
  themes:
  - samfunnssikkerhet  

faresone_skred_bratt_terreng:
  dataset_id: b2d5aaf8-79ac-40f3-9cd6-fdc30bc42ea1
  arcgis: https://nve.geodataonline.no/arcgis/rest/services/Skredfaresoner1/MapServer
  wms: https://nve.geodataonline.no/arcgis/services/Skredfaresoner1/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - Skredanalyseomraade  
    result_status: HIT-RED
    geolett_id: c37bac2a-1e32-49f8-b633-a305c166ec38
  properties:
  - skredOmrID
  - vurdertStatSannsynlighet
  - KARTLEGGINGSDATO
  themes:
  - samfunnssikkerhet   

tilfluktsrom_offentlige:
  dataset_id: dbae9aae-10e7-4b75-8d67-7f0e8828f3d8
  title: 'Tilfluktsrom - offentlige'
  wfs: https://wfs.geonorge.no/skwms1/wfs.tilfluktsrom_offentlige
  wms: https://ogc.dsb.no/wms.ashx
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/TilfluktsromOffentlige/20191001
  layers:
  - wfs: app:Tilfluktsrom
    wms: 
    - layer_340
    result_status: HIT-RED
  geom_element_name: app:posisjon
  properties:
  - app:romnr
  - app:plasser
  - app:adresse    
  themes:
  - samfunnssikkerhet 

# hensynssone_energianlegg:
#   wfs: https://wfs.geonorge.no/skwms1/wfs.nettanlegg?service=WFS
#   wms: https://nve.geodataonline.no/arcgis/services/Nettanlegg2/MapServer/WMSServer?
#   namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Nettanlegg/1.0
#   layers:
#   - wfs: app:EL_Luftlinje
#     wms: Distribusjonsnett,Regionalnett
#     result_status: HIT-RED
#     geolett_id: cc04ba06-1ad4-40cc-b961-389786a269ad
#   geom_element_name: app:linje
#   properties:
#   - app:navn
#   - app:nettnivå
#   - app:spenning
#   themes:
#   - samfunnssikkerhet    

arter_nasjonal_forvaltningsinteresse:
  dataset_id: a8456aed-441a-40c4-831f-46bcbe4e6ff1
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/artnasjonal2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/artnasjonal2/MapServer/WMSServer
  layers:
  - arcgis: 2
    wms: 
    - Alle_arter_av_sarlig_stor_forv_int_omr
    result_status: HIT-RED
  properties:
  - AntallObservasjoner
  - Gruppe
  - NorskNavn
  - Status
  - Faktaark 
  themes:
  - natur

kulturminner_enkeltminner:
  dataset_id: c72906a0-2bc2-41d7-bea2-c92d368e3c49
  wfs: https://wfs.geonorge.no/skwms1/wfs.kulturminner
  wms: https://kart.ra.no/wms/kulturminner
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/LokaliteterEnkeltminnerOgSikringssoner/20210217  
  layers:
  - wfs: app:Enkeltminne
    wms: 
    - Enkeltminner
    result_status: HIT-RED
  geom_element_name: app:område
  properties:
  - app:navn
  - app:kulturminneId
  - app:vernelov
  - app:verneparagraf
  - app:vernetype
  - app:vernedato
  - app:linkAskeladden
  - app:linkKulturminnesøk
  themes:
  - natur  

naturtyper_ku_verdi:
  dataset_id: 64cbb884-a19d-4356-a114-380cfe4a7314
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_kuverdi/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_kuverdi/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - kuverdi_svært_stor_verdi
    result_status: HIT-RED
    geolett_id: 3dd08517-af52-45db-a6ed-ac29b5d98fc4
    type_filter: Verdikategori = 'Svært stor verdi'
  - arcgis: 0
    wms: 
    - kuverdi_stor_verdi
    - kuverdi_middels_verdi
    - kuverdi_noe_verdi
    result_status: HIT-YELLOW
    type_filter: Verdikategori = 'Stor verdi' OR Verdikategori = 'Middels verdi' OR Verdikategori = 'Noe verdi'
  properties:
  - Naturtype
  - Verdikategori
  - Opphav
  - Nøyaktighetsklasse
  - Faktaark 
  themes:
  - natur

naturtyper_utvalgte_slåttemark:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 41c0fc6a-b938-4877-9a62-183ecba6cd48
    type_filter: UtvalgtNaturtypeKode = 'UN01'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark  
  themes:
  - natur

naturtyper_utvalgte_slåttemyr:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: f6e743f8-1081-469c-829c-f13201ec943c
    type_filter: UtvalgtNaturtypeKode = 'UN02'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark  
  themes:
  - natur  

naturtyper_utvalgte_hul_eik:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 5f93f5a9-84f8-4529-b5ae-5a02597d914b
    type_filter: UtvalgtNaturtypeKode = 'UN03'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark  
  themes:
  - natur

naturtyper_utvalgte_kalklindeskog:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: a2e49e65-2f5e-4188-b848-94cbc32315ff
    type_filter: UtvalgtNaturtypeKode = 'UN04'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark  
  themes:
  - natur  

naturtyper_utvalgte_kalksjøer:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 0f18bebe-9fe3-44dd-b6d1-b34e932ff438
    type_filter: UtvalgtNaturtypeKode = 'UN05'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark  
  themes:
  - natur

naturtyper_utvalgte_kystlynghei:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: ee52d09e-341b-493d-942b-09e5a218fdca
    type_filter: UtvalgtNaturtypeKode = 'UN06'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_kalkmark_boreonemoral:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms: 
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 39592497-57fc-418b-b3f1-8947aa8453b7
    type_filter: UtvalgtNaturtypeKode = 'UN07'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

farled:
  dataset_id: 8ff1538a-a93c-4391-8d6f-3555fc37819c
  wfs: https://wfs.geonorge.no/skwms1/wfs.farled
  wms: https://services.kystverket.no/wms.ashx?
  namespace: http://skjema.geonorge.no/SOSI/produktspesifikasjon/Farled/20210101
  layers:
  - wfs: app:HovedledOgBiledAreal
    wms: 
    - group_4
    result_status: HIT-RED
    geolett_id: 0c5dc043-e5b3-4349-8587-9b464d013aaa
  geom_element_name: app:lokalisering
  properties:
  - app:datauttaksdato
  themes:
  - samferdsel

# geoteknisk_borehull:
#   title: 'Geoteknisk borehull'
#   ogc_api: https://ogcapitest.ngu.no/rest/services/grunnundersokelser_utvidet/collections
#   wms: https://geo.ngu.no/geoserver/nadag/ows
#   layers:
#   - ogc_api: geotekniskborehull
#     wms: 
#     - GB_filter_komplette_data
#     result_status: HIT-RED
#   geom_element_name: posisjon
#   properties:
#   - kvikkleirePåvisning
#   - antallBorehullUndersøkelser
#   - høyde
#   - maksBoretLengde
#   themes:
#   - geologi


