stormflo:
  dataset_id: fbb95c67-623f-430a-9fa5-9cfcea8366b3
  wfs: https://wfs.geonorge.no/skwms1/wfs.stormflo_havniva
  wms: https://wms.geonorge.no/skwms1/wms.stormflo_havniva
  layers:
  - wfs: Stormflo20År_KlimaÅrNå
    wms:
    - stormflo20ar_klimaarna
    result_status: HIT-RED
    geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
  - wfs: Stormflo200År_KlimaÅrNå
    wms:
    - stormflo200ar_klimaarna
    result_status: HIT-YELLOW
    geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
  - wfs: Stormflo200År_KlimaÅr2100
    wms:
    - stormflo200ar_klimaar2100
    result_status: HIT-YELLOW
    geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
  geom_field: område
  properties:
  - sikkerhetsklasseFlom
  - oppdateringsdato
  - opphav
  themes:
  - samfunnssikkerhet

flomsoner:
  dataset_id: e95008fc-0945-4d66-8bc9-e50ab3f50401
  wfs: https://wfs.geonorge.no/skwms1/wfs.flomsoner
  wms: https://nve.geodataonline.no/arcgis/services/Flomsoner1/MapServer/WMSServer
  layers:
  - wfs: FlomAreal
    wms:
    - Flomsone_20arsflom
    - Flomsone_200arsflom
    - Flomsone_200arsflom_klima
    filter: gjentaksintervall IN [20, 200, 2100]
    result_status: HIT-RED
    geolett_id: 5adab8dc-b327-49ed-9336-e85fe2453a05
  geom_field: område
  properties:
  - gjentaksintervall
  - datauttaksdato
  themes:
  - samfunnssikkerhet

flom_aktsomhets_omr:
  dataset_id: 60c5024f-bf93-4d7a-888a-5fe001427195
  wfs: http://wfs.geonorge.no/skwms1/wfs.flomaktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/FlomAktsomhet/MapServer/WMSServer
  layers:
  - wfs: FlomAktsomhetOmr
    wms:
    - Flom_aktsomhetsomrade
    result_status: HIT-YELLOW
    geolett_id: 44ef4297-d5a5-4fab-9db3-d67429d7a5f0
  geom_field: område
  properties:
  - vassOmråde
  - temaKvalitet
  - vannKilde
  themes:
  - samfunnssikkerhet

jord_flomskred_aktsomhets_omr:
  dataset_id: 30e1883e-70e9-4510-9e97-00edbdcddc02
  wfs: https://wfs.geonorge.no/skwms1/wfs.jord_og_flomskred_aktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/SkredJordFlomAktR1/MapServer/WMSServer
  layers:
  - wfs: PotensieltSkredfareOmr
    wms:
    - Potensielt_Jord-Flomskredfare
    result_status: HIT-RED
    geolett_id: 643479b5-41d9-4d66-8069-18f746141a41
  geom_field: område
  properties:
  - skredType
  - skredfareVurdering
  - temaKvalitet
  - oppdateringsdato
  themes:
  - samfunnssikkerhet

snoskred_aktsomhets_omr:
  dataset_id: 54ada9d8-e6fc-48d6-82b0-5477166a4aaa
  wfs: https://wfs.geonorge.no/skwms1/wfs.snoskredaktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/SkredSnoAktR/MapServer/WMSServer
  layers:
  - wfs: PotensieltSkredfareOmr
    wms:
    - Snoskred-Aktsomhetsomrader
    result_status: HIT-RED
    geolett_id: 7831236b-c9c1-4d5f-af4b-cac0304d7d6e
  geom_field: område
  properties:
  - skredType
  - skredfareVurdering
  - temaKvalitet
  - oppdateringsdato
  themes:
  - samfunnssikkerhet

steinsprang_aktsomhets_omr:
  dataset_id: 02c6d51c-4e8c-4948-a620-dc046c8cb747
  wfs: https://wfs.geonorge.no/skwms1/wfs.steinsprang_aktsomhetsomrader
  wms: https://nve.geodataonline.no/arcgis/services/SkredSteinAktR/MapServer/WmsServer
  layers:
  - wfs: PotensieltSkredfareOmr
    wms:
    - Steinsprang-AktsomhetOmrader
    result_status: HIT-RED
    geolett_id: 2d405ce6-98ea-40f9-905b-f8a0d5c96224
  geom_field: område
  properties:
  - skredType
  - skredfareVurdering
  - temaKvalitet
  - oppdateringsdato
  themes:
  - samfunnssikkerhet

faresone_fjellskred:
  dataset_id: 17149f79-1289-4e3c-b964-94113eeb14c8
  arcgis: https://nve.geodataonline.no/arcgis/rest/services/Fjellskred1/MapServer
  wms: https://nve.geodataonline.no/arcgis/services/Fjellskred1/MapServer/WMSServer
  layers:
  - arcgis: 8
    wms:
    - Faresoner_fjellskred_sammensat
    result_status: HIT-RED
    geolett_id: a43cee7f-bcc4-44a9-b144-419a0c134a25
  properties:
  - skredOmrNavn
  - skredType
  - skredStatSannsynlighet
  themes:
  - samfunnssikkerhet

faresone_kvikkleireskred:
  dataset_id: b2d5aaf8-79ac-40f3-9cd6-fdc30bc42ea1
  arcgis: https://nve.geodataonline.no/arcgis/rest/services/SkredKvikkleire2/MapServer
  wms: https://nve.geodataonline.no/arcgis/services/SkredKvikkleire2/MapServer/WMSServer
  layers:
  - arcgis: 1
    wms:
    - KvikkleireRisiko
    result_status: HIT-RED
    geolett_id: 2e84d54f-9e93-4559-8214-8cb21567fa04
  properties:
  - skredOmrNavn
  - faregrad
  - konsekvens
  - risiko
  - rapportURL
  themes:
  - samfunnssikkerhet

faresone_skred_bratt_terreng:
  dataset_id: b2d5aaf8-79ac-40f3-9cd6-fdc30bc42ea1
  arcgis: https://nve.geodataonline.no/arcgis/rest/services/Skredfaresoner1/MapServer
  wms: https://nve.geodataonline.no/arcgis/services/Skredfaresoner1/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - Skredanalyseomraade
    result_status: HIT-RED
    geolett_id: c37bac2a-1e32-49f8-b633-a305c166ec38
  properties:
  - skredOmrID
  - vurdertStatSannsynlighet
  - KARTLEGGINGSDATO
  themes:
  - samfunnssikkerhet

tilfluktsrom_offentlige:
  dataset_id: dbae9aae-10e7-4b75-8d67-7f0e8828f3d8
  title: 'Tilfluktsrom - offentlige'
  wfs: https://wfs.geonorge.no/skwms1/wfs.tilfluktsrom_offentlige
  wms: https://ogc.dsb.no/wms.ashx
  layers:
  - wfs: Tilfluktsrom
    wms:
    - layer_340
    result_status: HIT-RED
  geom_field: posisjon
  properties:
  - romnr
  - plasser
  - adresse
  themes:
  - samfunnssikkerhet

hensynssone_energianlegg:
  dataset_id: 9f71a24b-9997-409f-8e42-ce6f0c62e073
  wfs: https://wfs.geonorge.no/skwms1/wfs.nettanlegg
  wms: https://nve.geodataonline.no/arcgis/services/Nettanlegg2/MapServer/WMSServer
  layers:
  - wfs: EL_Luftlinje
    wms:
    - Distribusjonsnett
    - Regionalnett
    result_status: HIT-RED
    geolett_id: cc04ba06-1ad4-40cc-b961-389786a269ad
  geom_field: linje
  properties:
  - navn
  - nettnivå
  - spenning
  themes:
  - samfunnssikkerhet

arter_nasjonal_forvaltningsinteresse:
  dataset_id: a8456aed-441a-40c4-831f-46bcbe4e6ff1
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/artnasjonal2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/artnasjonal2/MapServer/WMSServer
  layers:
  - arcgis: 2
    wms:
    - Alle_arter_av_sarlig_stor_forv_int_omr
    result_status: HIT-RED
  properties:
  - AntallObservasjoner
  - Gruppe
  - NorskNavn
  - Status
  - Faktaark
  themes:
  - natur

kulturminner_enkeltminner:
  dataset_id: c72906a0-2bc2-41d7-bea2-c92d368e3c49
  wfs: https://wfs.geonorge.no/skwms1/wfs.kulturminner
  wms: https://kart.ra.no/wms/kulturminner
  layers:
  - wfs: Enkeltminne
    wms:
    - Enkeltminner
    result_status: HIT-RED
  geom_field: område
  properties:
  - navn
  - kulturminneId
  - vernelov
  - verneparagraf
  - vernetype
  - vernedato
  - linkAskeladden
  - linkKulturminnesøk
  themes:
  - kulturminner

naturtyper_ku_verdi:
  dataset_id: 64cbb884-a19d-4356-a114-380cfe4a7314
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_kuverdi/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_kuverdi/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - kuverdi_svært_stor_verdi
    result_status: HIT-RED
    geolett_id: 3dd08517-af52-45db-a6ed-ac29b5d98fc4
    filter: Verdikategori = 'Svært stor verdi'
  - arcgis: 0
    wms:
    - kuverdi_stor_verdi
    - kuverdi_middels_verdi
    - kuverdi_noe_verdi
    result_status: HIT-YELLOW
    filter: Verdikategori = 'Stor verdi' OR Verdikategori = 'Middels verdi' OR Verdikategori = 'Noe verdi'
  properties:
  - Naturtype
  - Verdikategori
  - Opphav
  - Nøyaktighetsklasse
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_slåttemark:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 41c0fc6a-b938-4877-9a62-183ecba6cd48
    filter: UtvalgtNaturtypeKode = 'UN01'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_slåttemyr:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: f6e743f8-1081-469c-829c-f13201ec943c
    filter: UtvalgtNaturtypeKode = 'UN02'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_hul_eik:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 5f93f5a9-84f8-4529-b5ae-5a02597d914b
    filter: UtvalgtNaturtypeKode = 'UN03'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_kalklindeskog:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: a2e49e65-2f5e-4188-b848-94cbc32315ff
    filter: UtvalgtNaturtypeKode = 'UN04'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_kalksjøer:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 0f18bebe-9fe3-44dd-b6d1-b34e932ff438
    filter: UtvalgtNaturtypeKode = 'UN05'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_kystlynghei:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: ee52d09e-341b-493d-942b-09e5a218fdca
    filter: UtvalgtNaturtypeKode = 'UN06'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

naturtyper_utvalgte_kalkmark_boreonemoral:
  dataset_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
  arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
  wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
  layers:
  - arcgis: 0
    wms:
    - naturtype_utvalgt_omr
    result_status: HIT-RED
    geolett_id: 39592497-57fc-418b-b3f1-8947aa8453b7
    filter: UtvalgtNaturtypeKode = 'UN07'
  properties:
  - Områdenavn
  - UtvalgtNaturtype
  - Nøyaktighetsklasse
  - Registreringsdato
  - Faktaark
  themes:
  - natur

farled:
  dataset_id: 8ff1538a-a93c-4391-8d6f-3555fc37819c
  wfs: https://wfs.geonorge.no/skwms1/wfs.farled
  wms: https://services.kystverket.no/wms.ashx
  layers:
  - wfs: HovedledOgBiledAreal
    wms:
    - group_4
    result_status: HIT-RED
    geolett_id: 0c5dc043-e5b3-4349-8587-9b464d013aaa
  geom_field: lokalisering
  properties:
  - datauttaksdato
  themes:
  - samferdsel

geoteknisk_borehull:
  dataset_id: bf45a463-434d-4b4d-84dc-9325780ab5fb
  title: 'Geoteknisk borehull'
  ogc_api: https://ogcapitest.ngu.no/rest/services/grunnundersokelser_utvidet/collections
  wms: https://geo.ngu.no/geoserver/nadag/ows
  layers:
  - ogc_api: geotekniskborehull
    wms:
    - GB_filter_komplette_data
    result_status: HIT-YELLOW
  geom_field: posisjon
  properties:
  - kvikkleirePåvisning
  - antallBorehullUndersøkelser
  - høyde
  - maksBoretLengde
  themes:
  - geologi

reindrift_flyttlei:
  dataset_id: f9c1e228-892f-4f1a-9e4e-b6d6149f373c
  wfs: https://wfs02.nibio.no/cgi-bin/rein/flyttlei
  wms: https://reindrift.nibio.no/cgi-bin/reindrift
  layers:
  - wfs: Flyttlei
    wms:
    - Flyttlei
    result_status: HIT-RED
  geom_field: msGeometry
  properties:
  - distriktnavn
  - beitebrukerstreng
  - kvalitetssikret
  - oppdateringsdato
  themes:
  - landbruk

reindrift_trekklei:
  dataset_id: 95b0d396-a6fe-462b-8753-120efd0b60f3
  wfs: https://wfs02.nibio.no/cgi-bin/rein/trekklei
  wms: https://reindrift.nibio.no/cgi-bin/reindrift
  layers:
  - wfs: Trekklei
    wms:
    - Trekklei
    result_status: HIT-RED
  geom_field: msGeometry
  properties:
  - distriktnavn
  - beitebrukerstreng
  - kvalitetssikret
  - oppdateringsdato
  themes:
  - landbruk

reindrift_oppsamlingsområde:
  dataset_id: a02e84ec-322c-47a7-a626-ca02d57d1f7e
  wfs: https://wfs02.nibio.no/cgi-bin/rein/oppsamlingsomrade
  wms: https://reindrift.nibio.no/cgi-bin/reindrift
  layers:
  - wfs: Oppsamlingsomrade
    wms:
    - Oppsamling
    result_status: HIT-RED
  geom_field: msGeometry
  properties:
  - distriktnavn
  - beitebrukerstreng
  - kvalitetssikret
  - oppdateringsdato
  themes:
  - landbruk

reindrift_reindriftsanlegg:
  dataset_id: 8dfa67c5-3099-4353-9ce0-72f9ebd44a2c
  wfs: https://wfs02.nibio.no/cgi-bin/rein/reindriftsanlegg
  wms: https://reindrift.nibio.no/cgi-bin/reindrift
  layers:
  - wfs: ReindriftsAnleggPunkt
    wms:
    - Anlegg
    result_status: HIT-RED
  geom_field: msGeometry
  properties:
  - distriktnavn
  - beitebrukerstreng
  - kodenavn
  - definisjon
  - kvalitetssikret
  - oppdateringsdato
  themes:
  - landbruk
