---

type: dataset
dataset_id: b2d5aaf8-79ac-40f3-9cd6-fdc30bc42ea1
name: faresone_skred_bratt_terreng

arcgis: https://nve.geodataonline.no/arcgis/rest/services/Skredfaresoner1/MapServer
wms: https://nve.geodataonline.no/arcgis/services/Skredfaresoner1/MapServer/WMSServer
layers:
- arcgis: '0'
  wms:
  - Skredanalyseomraade
  result_status: HIT-RED
  geolett_id: c37bac2a-1e32-49f8-b633-a305c166ec38
properties:
- skredOmrID
- vurdertStatSannsynlighet
- KARTLEGGINGSDATO
themes:
- samfunnssikkerhet
