---

type: dataset
dataset_id: 8ff1538a-a93c-4391-8d6f-3555fc37819c
name: farled

wfs: https://wfs.geonorge.no/skwms1/wfs.farled
wms: https://services.kystverket.no/wms.ashx
layers:
- wfs: HovedledOgBiledAreal
  wms:
  - group_4
  result_status: HIT-RED
  geolett_id: 0c5dc043-e5b3-4349-8587-9b464d013aaa
geom_field: lokalisering
properties:
- datauttaksdato
themes:
- samferdsel
