---

type: dataset
config_id: c38052f3-2c3d-4ce6-9be0-3f06d67cf8eb
name: referanseruter
disabled: true

metadata_id: 25b83fc1-f2bd-4052-bd2d-bd949ac0f402
wfs: TODO - har ikke
wms: TODO - har ikke
layers:
- wfs: Referanseruter
  wms:
  - referanseruter
  result_status: HIT-RED
  planning_guidance_id: 0cdcda80-d153-495c-afe4-ad26634a4274
geom_field: lokalisering
properties:
- todo
themes:
- samferdsel
