---

type: dataset
config_id: 4dabf857-10f3-47d3-9567-6f959053da58
name: navigasjonsinstallasjon
disabled: true

metadata_id: 94b8c392-e2c8-426a-8dbe-ae828049a1df
wfs: https://nfs.kystverket.no/arcgis/services/nfs/NFSSistOperativ/MapServer/WFSServer
wms: https://nfs.kystverket.no/arcgis/services/nfs/NFSSistOperativ/MapServer/WMSServer
layers:
- wfs: Lys
  # ønsker liste med flere lag Lys,IB,Sektorlinje,Lyssektor,Racon,Fastsjømerke,Flytendemerke,Overettlinje__lys,Overettlinje__merke
  wms:
  - NAVIGASJONSINSTALLASJONER
  result_status: HIT-RED
  planning_guidance_id: 10b26fef-ddf2-4d13-91bc-d0c199a012a2
geom_field: SHAPE
properties:
- Kategori
- SjomerkeNr
- navn
themes:
- samferdsel
