---

type: dataset
config_id: c74656bb-267d-4546-aa14-6323070d06c7
name: naturtyper_ku_verdi

metadata_id: 64cbb884-a19d-4356-a114-380cfe4a7314
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_kuverdi/MapServer
wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_kuverdi/MapServer/WMSServer
layers:
- arcgis: '0'
  wms:
  - kuverdi_svært_stor_verdi
  result_status: HIT-RED
  geolett_id: 9d803106-57f6-494e-bca8-67f1fd1f72a3
  veiledning_bygg_id: 522da012-1633-40c5-ad96-e4784d278401
  filter: Verdikategori = 'Svært stor verdi'
- arcgis: '0'
  wms:
  - kuverdi_stor_verdi
  result_status: HIT-RED
  geolett_id: cfbd9296-6624-4822-ac40-ee8492ec88ca
  filter: Verdikategori = 'Stor verdi'
- arcgis: '0'
  wms:
  - kuverdi_middels_verdi
  result_status: HIT-YELLOW
  geolett_id: 3db0182e-7bff-44d2-a8f8-e312b303d6cf
  filter: Verdikategori = 'Middels verdi'
- arcgis: '0'
  wms:
  - kuverdi_noe_verdi
  result_status: HIT-YELLOW
  geolett_id: bc86e470-6789-4abf-95f2-3cdba521b5fe
  filter: Verdikategori = 'Noe verdi'
properties:
- Naturtype
- Verdikategori
- Opphav
- Nøyaktighetsklasse
- Faktaark
themes:
- natur
---

type: quality
dataset_id: c74656bb-267d-4546-aa14-6323070d06c7

indicators:
- type: object
  quality_dimension_id: stedfestingsnøyaktighet
  quality_dimension_name: Stedfestingsnøyaktighet
  quality_warning_text: Stedfestingsnøyaktighet er usikker på et eller flere objekter
  property: Nøyaktighetsklasse
  warning_threshold: Mindre god (> 50m)

- type: coverage
  quality_dimension_id: fullstendighet_dekning
  quality_dimension_name: Fullstendighetsdekning
  quality_warning_text: Området er ikke kartlagt for naturtyper
  warning_threshold: null
  arcgis:
    url: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_nin/MapServer
    layer: '1'
    property: Dekningskartverdi
    veiledning_bygg_id: 45ece8ff-e382-4c40-b469-045e2939f554
    veiledning_plan_id: 0685b79a-76a8-439a-8793-6dc31a0a9099
    properties:
    - Prosjektnavn
    - Dekningskartverdi
    - Årstall
    - Kartleggingsinstruks
    - Prosjektrapport