---

type: dataset
config_id: 7ea189bc-0b59-4742-8260-5bfd3bfaa510
name: naturtyper_utvalgte_kystlynghei

metadata_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
layers:
- arcgis: '0'
  wms:
  - naturtype_utvalgt_omr
  result_status: HIT-RED
  planning_guidance_id: ee52d09e-341b-493d-942b-09e5a218fdca
  filter: UtvalgtNaturtypeKode = 'UN06'
properties:
- Områdenavn
- UtvalgtNaturtype
- Nøyaktighetsklasse
- Registreringsdato
- Faktaark
themes:
- natur
