---

type: dataset
config_id: e85af2f1-eebe-4777-932e-ff240095c194
name: naturtyper_utvalgte_kalklindeskog

metadata_id: 2c0072de-f702-401e-bfb3-5ad3d08d4c2d
arcgis: https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_utvalgte2/MapServer
wms: https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte2/MapServer/WMSServer
layers:
- arcgis: '0'
  wms:
  - naturtype_utvalgt_omr
  result_status: HIT-RED
  planning_guidance_id: a2e49e65-2f5e-4188-b848-94cbc32315ff
  filter: UtvalgtNaturtypeKode = 'UN04'
properties:
- Områdenavn
- UtvalgtNaturtype
- Nøyaktighetsklasse
- Registreringsdato
- Faktaark
themes:
- natur
