---

type: dataset
dataset_id: 94b8c392-e2c8-426a-8dbe-ae828049a1df
name: Navigasjonsinstallasjon

metadata_id: 94b8c392-e2c8-426a-8dbe-ae828049a1df
wfs: https://nfs.kystverket.no/arcgis/services/nfs/NFSSistOperativ/MapServer/WFSServer
wms: https://nfs.kystverket.no/arcgis/services/nfs/NFSSistOperativ/MapServer/WMSServer
layers:
- wfs: nfs_NFSSistOperativ:Lys
  wms:
  - NAVIGASJONSINSTALLASJONER
  result_status: HIT-RED
  geolett_id: 2afd368b-42ff-4918-87c1-c9f6231cd8d0
geom_field: lokalisering
properties:
- datauttaksdato
themes:
- samferdsel
