---

type: dataset
config_id: 68a9f9a1-07db-4e4b-8de5-92cb7d4aff1c
name: faresone_fjellskred

metadata_id: 17149f79-1289-4e3c-b964-94113eeb14c8
arcgis: https://nve.geodataonline.no/arcgis/rest/services/Fjellskred1/MapServer
wms: https://nve.geodataonline.no/arcgis/services/Fjellskred1/MapServer/WMSServer
layers:
- arcgis: '8'
  wms:
  - Faresoner_fjellskred_sammensat
  result_status: HIT-RED
  planning_guidance_id: a43cee7f-bcc4-44a9-b144-419a0c134a25
  building_guidance_id: a43cee7f-bcc4-44a9-b144-419a0c134a25
properties:
- skredOmrNavn
- skredType
- skredStatSannsynlighet
themes:
- samfunnssikkerhet
