---

type: dataset
config_id: f5e9ac5c-2d1e-43eb-ac8a-da918d922584
name: kulturminner_enkeltminner_ikkev

metadata_id: c72906a0-2bc2-41d7-bea2-c92d368e3c49
ogc_api: https://api.ra.no/LokaliteterEnkeltminnerOgSikringssoner/collections
wms: https://kart.ra.no/wms/kulturminner
layers:
- ogc_api: enkeltminner
  wms:
  - Enkeltminner
  result_status: HIT-RED
  planning_guidance_id: ccf12fba-2931-4a21-a6ce-28f7c188d762
  building_guidance_id: c65f324d-73b1-41ad-bf0f-e24573da1871
  filter: vernetype = 'IKKEV' AND enkeltminnekategori IN ('E-ARK', 'E-BER', 'E-MAR', 'E-RUI')
geom_field: område
properties:
- navn
- kulturminneId
- vernelov
- verneparagraf
- vernetype
- vernedato
- enkeltminnekategori
- linkAskeladden
- linkKulturminnesøk
themes:
- kulturminner
