---

type: dataset
config_id: 55747d23-8ced-47ee-811f-6bc396bfaf09
name: kulturminner_enkeltminner_fje

metadata_id: c72906a0-2bc2-41d7-bea2-c92d368e3c49
ogc_api: https://api.ra.no/LokaliteterEnkeltminnerOgSikringssoner/collections
wms: https://kart.ra.no/wms/kulturminner
layers:
- ogc_api: enkeltminner
  wms:
  - Enkeltminner
  result_status: HIT-RED
  planning_guidance_id: 550b9023-6f93-4175-aebf-e8c2f754b288
  building_guidance_id: 87969cd5-ed0c-431c-a9bd-08d2e634a316
  filter: vernetype = 'FJE' AND enkeltminnekategori IN ('E-ARK', 'E-BER', 'E-MAR', 'E-RUI')
geom_field: område
properties:
- navn
- kulturminneId
- vernelov
- verneparagraf
- vernetype
- vernedato
- enkeltminnekategori
- linkAskeladden
- linkKulturminnesøk
themes:
- kulturminner
