---

type: dataset
dataset_id: fbb95c67-623f-430a-9fa5-9cfcea8366b3
name: stormflo

wfs: https://wfs.geonorge.no/skwms1/wfs.stormflo_havniva
wms: https://wms.geonorge.no/skwms1/wms.stormflo_havniva
layers:
- wfs: Stormflo20År_KlimaÅrNå
  wms:
  - stormflo20ar_klimaarna
  result_status: HIT-RED
  geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
- wfs: Stormflo200År_KlimaÅrNå
  wms:
  - stormflo200ar_klimaarna
  result_status: HIT-YELLOW
  geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
- wfs: Stormflo200År_KlimaÅr2100
  wms:
  - stormflo200ar_klimaar2100
  result_status: HIT-YELLOW
  geolett_id: a150a588-6b48-415b-aa18-2c5c683bf18c
geom_field: område
properties:
- sikkerhetsklasseFlom
- oppdateringsdato
- opphav
themes:
- samfunnssikkerhet
---

type: quality
dataset_id: fbb95c67-623f-430a-9fa5-9cfcea8366b3

indicators:
- type: coverage
  quality_dimension_id: fullstendighet_dekning
  quality_dimension_name: Fullstendighetsdekning
  quality_warning_text: Området er ikke kartlagt
  warning_threshold: ikkeKartlagt
  wfs:
    url: https://wfs.geonorge.no/skwms1/wfs.stormflo_havniva
    layer: Dekningsområde
    geom_field: område
    property: dekningStatus
