egnethet_reguleringsplan:
  type: dataset
  quality_dimension_id: Egnethet
  quality_dimension_name: Egnethet for reguleringsplan
  quality_warning_text: Datasett er lite egnet for reguleringsplan
  warning_threshold: 1|2 
  input_filter: context = 'Reguleringsplan'  
  value: 4 (God)

stedfestingsnøyaktighet:
  type: object
  quality_dimension_id: stedfestingsnøyaktighet
  quality_dimension_name: Stedfestingsnøyaktighet
  quality_warning_text: Data kan være utfordrende å bruke i plan- eller byggesak
  warning_threshold: Mindre god (> 50m)
  property: Nøyaktighetsklasse
